<h1>Hello, I'm Helpdesk Tickets!</h1>
<ul>
	<li>No.1</li>
	<li>No.2</li>
	<li>No.3</li>
	<li>No.4</li>
	<li>No.5</li>
</ul>
<div class="atopt-helpdesk-ticket-index">
    <form
        id="form-validate"
        action="<?php echo $block->getUrl('helpdesk/ticket/save') ?>"
        method="post">
        <?php echo $block->getBlockHtml('formkey') ?>
        <fieldset class="fieldset">
            <div class="field title required">
                <label class="label" for="title"><span><?php echo __('Title') ?></span></label>
                <div class="control">
                    <input
                        id="title"
                        type="text"
                        name="title"
                        data-validate="{required:true}"
                        value=""
                        placeholder="<?php echo __('Something descriptive') ?>" />
                </div>
            </div>
            <div class="field severity">
                <label class="label" for="severity"><span><?php echo __('Severity') ?></span></label>
                <div class="control">
                    <select name="severity">
                        <?php foreach ($block->getSeverities() as $severity): ?>
                            <option value="<?php echo $severity['value'] ?>"><?php echo $this->escapeHtml($severity['label']) ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action save primary">
                    <span><?php echo __('Submit Ticket') ?></span>
                </button>
            </div>
        </div>
    </form>

    <script>
        require([
            'jquery',
            'mage/mage'
        ], function($){
            var dataForm = $('#form-validate');
            dataForm.mage('validation', {});
        });
    </script>
 </div>